# Generated by Django 5.2.17 on 2026-09-24 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['display_order', 'display_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['display_order', 'display_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['display_order', 'display_name'],
                'abstract': False,
            },
        ),
    ]
