# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationindex',
            options={'ordering': ['display_order', 'display_name'], 'verbose_name': '成果索引', 'verbose_name_plural': '成果索引'},
        ),
        migrations.AlterModelOptions(
            name='publicationtype',
            options={'ordering': ['display_order', 'display_name'], 'verbose_name': '成果類型', 'verbose_name_plural': '成果類型'},
        ),
        migrations.AlterModelOptions(
            name='researchfield',
            options={'ordering': ['display_order', 'display_name'], 'verbose_name': '研究領域', 'verbose_name_plural': '研究領域'},
        ),
    ]
