# Generated by Django 5.2.17 on 2026-09-24 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctoral_students', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdvisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advisor_role', models.CharField(choices=[('primary', '主指導'), ('co_advisor', '共同指導'), ('other', '其他')], db_index=True, default='primary', max_length=16)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_relations', to='professors.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor_relations', to='doctoral_students.doctoralstudentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='idx_student_active')],
            },
        ),
    ]
