# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentadvisor',
            options={'verbose_name': '學生指導關係', 'verbose_name_plural': '學生指導關係'},
        ),
    ]
