# Generated by Django 5.2.17 on 2026-09-24 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctoralStudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('admission_year', models.PositiveSmallIntegerField(db_index=True)),
                ('enrollment_status', models.CharField(choices=[('active', '在學'), ('leave', '休學'), ('graduated', '畢業'), ('withdrawn', '退學'), ('archived', '封存')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_students', to='taxonomy.researchfield')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctoral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
