# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctoral_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoralstudentprofile',
            options={'verbose_name': '博士生', 'verbose_name_plural': '博士生'},
        ),
    ]
