# Generated by Django 5.2.17 on 2026-10-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctoral_students', '0002_alter_doctoralstudentprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudentprofile',
            name='admission_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
