# Generated by Django 5.2.17 on 2026-09-24 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(db_index=True, max_length=16)),
                ('to_status', models.CharField(db_index=True, max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_transitions', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='publications.publicationrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['publication', 'created_at'], name='idx_pub_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='ck_status_change')],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', '核准'), ('return', '退回'), ('archive', '封存')], db_index=True, max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('visibility_after', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='publications.publicationrecord')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['publication', 'created_at'], name='idx_review_pub_time')],
            },
        ),
    ]
