# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_add_revoke_decision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationtransition',
            options={'verbose_name': '成果狀態轉換', 'verbose_name_plural': '成果狀態轉換'},
        ),
        migrations.AlterModelOptions(
            name='reviewdecision',
            options={'verbose_name': '審核決定', 'verbose_name_plural': '審核決定'},
        ),
    ]
