# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': '稽核紀錄', 'verbose_name_plural': '稽核紀錄'},
        ),
    ]
