# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': '使用者角色', 'verbose_name_plural': '使用者角色'},
        ),
    ]
