# Generated by Django 5.2.17 on 2026-09-24 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctoral_students', '0001_initial'),
        ('professors', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFieldAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomy.researchfield')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationIndexAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomy.publicationindex')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('normalized_title', models.CharField(db_index=True, editable=False, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('journal_or_conference_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('language', models.CharField(db_index=True, default='zh-Hant', max_length=16)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('normalized_doi', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('issn', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('volume', models.CharField(blank=True, max_length=32)),
                ('issue', models.CharField(blank=True, max_length=32)),
                ('pages_or_article_number', models.CharField(blank=True, max_length=64)),
                ('publication_stage', models.CharField(choices=[('submitted', '投稿中'), ('accepted', '已接受'), ('online_first', '線上先行'), ('published', '正式發表')], db_index=True, default='published', max_length=16)),
                ('submitted_to_journal_date', models.DateField(blank=True, db_index=True, null=True)),
                ('accepted_date', models.DateField(blank=True, db_index=True, null=True)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('workflow_status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已送審'), ('returned', '已退回'), ('approved', '已核准'), ('archived', '已封存'), ('withdrawn', '已撤回')], db_index=True, default='draft', max_length=16)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('visibility_scope', models.CharField(choices=[('public', '公開'), ('department', '系所內'), ('owner_advisor', '本人與指導教授'), ('staff_only', '工作人員限定')], db_index=True, default='owner_advisor', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_publications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_publications', to=settings.AUTH_USER_MODEL)),
                ('indices', models.ManyToManyField(blank=True, through='publications.PublicationIndexAssignment', to='taxonomy.publicationindex')),
                ('owner_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='doctoral_students.doctoralstudentprofile')),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='taxonomy.publicationtype')),
                ('research_fields', models.ManyToManyField(blank=True, through='publications.PublicationFieldAssignment', to='taxonomy.researchfield')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publicationindexassignment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.publicationrecord'),
        ),
        migrations.AddField(
            model_name='publicationfieldassignment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.publicationrecord'),
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('affiliation', models.CharField(blank=True, db_index=True, max_length=500)),
                ('author_order', models.PositiveSmallIntegerField()),
                ('is_corresponding_author', models.BooleanField(db_index=True, default=False)),
                ('orcid', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('linked_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_publications', to='professors.professor')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='publications.publicationrecord')),
            ],
            options={
                'ordering': ['author_order'],
            },
        ),
        migrations.AddIndex(
            model_name='publicationrecord',
            index=models.Index(fields=['owner_student', 'workflow_status'], name='idx_owner_status'),
        ),
        migrations.AddIndex(
            model_name='publicationrecord',
            index=models.Index(fields=['workflow_status', 'publication_date', 'publication_type'], name='idx_staff_stats'),
        ),
        migrations.AddIndex(
            model_name='publicationrecord',
            index=models.Index(fields=['workflow_status', 'is_published', 'visibility_scope'], name='idx_public_gate'),
        ),
        migrations.AddConstraint(
            model_name='publicationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_doi__isnull', False)), fields=('normalized_doi',), name='uq_doi_normalized'),
        ),
        migrations.AddConstraint(
            model_name='publicationindexassignment',
            constraint=models.UniqueConstraint(fields=('publication', 'index'), name='uq_publication_index'),
        ),
        migrations.AddConstraint(
            model_name='publicationfieldassignment',
            constraint=models.UniqueConstraint(fields=('publication', 'field'), name='uq_publication_field'),
        ),
        migrations.AddConstraint(
            model_name='publicationauthor',
            constraint=models.UniqueConstraint(fields=('publication', 'author_order'), name='uq_author_order'),
        ),
        migrations.AddConstraint(
            model_name='publicationauthor',
            constraint=models.CheckConstraint(condition=models.Q(('author_order__gte', 1)), name='ck_author_order_positive'),
        ),
    ]
