# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_reconcile_official_versions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationauthor',
            options={'ordering': ['author_order'], 'verbose_name': '成果作者', 'verbose_name_plural': '成果作者'},
        ),
        migrations.AlterModelOptions(
            name='publicationfieldassignment',
            options={'verbose_name': '成果研究領域對照', 'verbose_name_plural': '成果研究領域對照'},
        ),
        migrations.AlterModelOptions(
            name='publicationindexassignment',
            options={'verbose_name': '成果索引對照', 'verbose_name_plural': '成果索引對照'},
        ),
        migrations.AlterModelOptions(
            name='publicationrecord',
            options={'verbose_name': '成果紀錄', 'verbose_name_plural': '成果紀錄'},
        ),
        migrations.AlterModelOptions(
            name='publicationseries',
            options={'verbose_name': '成果系列', 'verbose_name_plural': '成果系列'},
        ),
    ]
