# Generated by Django 5.2.17 on 2026-10-01 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_controlled_reference_data(apps, schema_editor):
    Goal = apps.get_model("publications", "SustainableDevelopmentGoal")
    Mode = apps.get_model("publications", "ConferencePresentationMode")
    Country = apps.get_model("publications", "Country")
    for order, (code, label) in enumerate([
        ("SDG01", "SDG01 消除貧窮"), ("SDG02", "SDG02 消除飢餓"),
        ("SDG03", "SDG03 健康與福祉"), ("SDG04", "SDG04 優質教育"),
        ("SDG05", "SDG05 性別平權"), ("SDG06", "SDG06 淨水及衛生"),
        ("SDG07", "SDG07 可負擔能源"), ("SDG08", "SDG08 合適的工作及經濟成長"),
        ("SDG09", "SDG09 工業、創新及基礎建設"), ("SDG10", "SDG10 減少不平等"),
        ("SDG11", "SDG11 永續城鄉"), ("SDG12", "SDG12 責任消費及生產"),
        ("SDG13", "SDG13 氣候行動"), ("SDG14", "SDG14 海洋生態"),
        ("SDG15", "SDG15 陸域生態"), ("SDG16", "SDG16 和平、正義及健全制度"),
        ("SDG17", "SDG17 夥伴關係"), ("NONE", "無"),
    ], 1):
        Goal.objects.get_or_create(code=code, defaults={"display_name": label, "display_order": order})
    for order, (code, label) in enumerate([
        ("keynote_speaker", "Keynote speaker"), ("invited_speaker", "Invited speaker"),
        ("session_chairman", "Session chairman"), ("oral", "Oral"), ("poster", "Poster"),
        ("abstract", "Abstract"), ("article", "Article"), ("attendance_only", "僅與會"),
    ], 1):
        Mode.objects.get_or_create(code=code, defaults={"display_name": label, "display_order": order})
    # The supplied exports establish these legacy codes.  A full country master
    # remains deliberately out of this migration until the secretary supplies it.
    for order, (code, zh, en) in enumerate([
        ("0", "中華民國", "R.O.C."), ("9", "印尼", "Indonesia"),
        ("13", "日本", "Japan"), ("15", "南韓", "Republic of Korea"),
        ("27", "新加坡", "Singapore"), ("104", "紐西蘭", "New Zealand"),
        ("329", "瑞士", "Switzerland"), ("330", "英國", "United Kingdom"),
        ("403", "加拿大", "Canada"), ("425", "美國", "United States of America"),
        ("A00", "未提供", ""),
    ], 1):
        Country.objects.get_or_create(code=code, defaults={"zh_name": zh, "en_name": en, "display_order": order})


def unseed_controlled_reference_data(apps, schema_editor):
    # Reference records may already be in use; preserve them on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publicationauthor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePresentationMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('keynote_speaker', 'Keynote speaker'), ('invited_speaker', 'Invited speaker'), ('session_chairman', 'Session chairman'), ('oral', 'Oral'), ('poster', 'Poster'), ('abstract', 'Abstract'), ('article', 'Article'), ('attendance_only', '僅與會')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '會議發表方式',
                'verbose_name_plural': '會議發表方式',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('zh_name', models.CharField(db_index=True, max_length=100)),
                ('en_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '國家／地區',
                'verbose_name_plural': '國家／地區',
                'ordering': ['display_order', 'zh_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SDG01', 'SDG01 消除貧窮'), ('SDG02', 'SDG02 消除飢餓'), ('SDG03', 'SDG03 健康與福祉'), ('SDG04', 'SDG04 優質教育'), ('SDG05', 'SDG05 性別平權'), ('SDG06', 'SDG06 淨水及衛生'), ('SDG07', 'SDG07 可負擔能源'), ('SDG08', 'SDG08 合適的工作及經濟成長'), ('SDG09', 'SDG09 工業、創新及基礎建設'), ('SDG10', 'SDG10 減少不平等'), ('SDG11', 'SDG11 永續城鄉'), ('SDG12', 'SDG12 責任消費及生產'), ('SDG13', 'SDG13 氣候行動'), ('SDG14', 'SDG14 海洋生態'), ('SDG15', 'SDG15 陸域生態'), ('SDG16', 'SDG16 和平、正義及健全制度'), ('SDG17', 'SDG17 夥伴關係'), ('NONE', '無')], max_length=8, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '永續發展目標',
                'verbose_name_plural': '永續發展目標',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_type', models.CharField(choices=[('international', '國際研討會'), ('domestic', '國內研討會')], max_length=16)),
                ('organizer', models.CharField(max_length=500)),
                ('location_city', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('received_subsidy', models.BooleanField(default=False)),
                ('presented_paper', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conference_detail', to='publications.publicationrecord')),
                ('location_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_locations', to='publications.country')),
            ],
            options={
                'verbose_name': '學術會議明細',
                'verbose_name_plural': '學術會議明細',
            },
        ),
        migrations.CreateModel(
            name='JournalArticleDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_type', models.CharField(choices=[('tssci', 'TSSCI'), ('sci', 'SCI'), ('ssci', 'SSCI'), ('ei', 'EI'), ('ahci', 'A&HCI'), ('thci', 'THCI'), ('scopus', 'Scopus'), ('college_recognized', '各院認可之優良期刊'), ('other', '其他')], db_index=True, max_length=24)),
                ('legacy_journal_type', models.CharField(blank=True, editable=False, max_length=255)),
                ('international_journal_rank', models.CharField(blank=True, choices=[('top_10', '前 10%'), ('top_10_25', '10–25%'), ('top_25_50', '25–50%'), ('bottom_50_or_unranked', '後 50% 或未有排名')], max_length=24)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('taiwan_journal_level', models.CharField(blank=True, choices=[('level_1', '第一級'), ('level_2', '第二級'), ('other', '非第一級及第二級')], max_length=16)),
                ('custom_journal_type', models.CharField(blank=True, max_length=255)),
                ('student_author_order', models.CharField(choices=[('first', '第一作者'), ('second', '第二作者'), ('third', '第三作者'), ('fourth_or_later', '第四作者（含）以後')], max_length=20)),
                ('student_author_order_reason', models.CharField(blank=True, max_length=500)),
                ('student_author_attribute', models.CharField(choices=[('first_author', '第一作者'), ('corresponding_author', '通訊作者'), ('co_first_or_co_corresponding', '共同第一作者或共同通訊作者'), ('neither', '非第一或通訊作者')], max_length=32)),
                ('is_student_corresponding_author', models.BooleanField(default=False)),
                ('has_international_collaboration', models.BooleanField(default=False)),
                ('publication_medium', models.CharField(choices=[('paper', '紙本期刊'), ('electronic', '電子期刊'), ('paper_and_electronic', '紙本及電子期刊')], max_length=24)),
                ('paper_nature', models.CharField(choices=[('academic', '學術'), ('educational', '學習教育'), ('practical', '實務')], max_length=16)),
                ('paper_attribute', models.CharField(choices=[('theoretical', '理論'), ('applied', '應用'), ('other', '其他')], max_length=16)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('is_annual_representative_work', models.BooleanField(default=False)),
                ('is_peer_reviewed', models.BooleanField(default=False)),
                ('citation_count', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_place', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal_detail', to='publications.publicationrecord')),
                ('publication_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_publications', to='publications.country')),
            ],
            options={
                'verbose_name': '期刊論文明細',
                'verbose_name_plural': '期刊論文明細',
            },
        ),
        migrations.CreateModel(
            name='ConferencePresentationModeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentation_mode_assignments', to='publications.conferencedetail')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_assignments', to='publications.conferencepresentationmode')),
            ],
            options={
                'verbose_name': '會議發表方式對照',
                'verbose_name_plural': '會議發表方式對照',
                'constraints': [models.UniqueConstraint(fields=('conference', 'mode'), name='uq_conference_presentation_mode')],
            },
        ),
        migrations.CreateModel(
            name='ConferenceParticipantCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_country_assignments', to='publications.conferencedetail')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_participations', to='publications.country')),
            ],
            options={
                'verbose_name': '會議與會國家',
                'verbose_name_plural': '會議與會國家',
                'constraints': [models.UniqueConstraint(fields=('conference', 'country'), name='uq_conference_participant_country')],
            },
        ),
        migrations.CreateModel(
            name='PublicationSDGAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sdg_assignments', to='publications.publicationrecord')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_assignments', to='publications.sustainabledevelopmentgoal')),
            ],
            options={
                'verbose_name': '成果 SDG 對照',
                'verbose_name_plural': '成果 SDG 對照',
                'constraints': [models.UniqueConstraint(fields=('publication', 'goal'), name='uq_publication_sdg')],
            },
        ),
        migrations.RunPython(seed_controlled_reference_data, unseed_controlled_reference_data),
    ]
