# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': '教授', 'verbose_name_plural': '教授'},
        ),
    ]
