# Generated by Django 5.2.17 on 2026-09-24 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('article_fulltext', '論文全文'), ('acceptance_letter', '接受函'), ('journal_proof', '期刊佐證'), ('index_proof', '索引佐證'), ('conference_proof', '會議佐證'), ('other', '其他')], db_index=True, default='other', max_length=24)),
                ('original_filename', models.CharField(db_index=True, max_length=500)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(db_index=True, max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='publications.publicationrecord')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='documents.sourcedocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['publication', 'is_active'], name='idx_doc_publication_active')],
                'constraints': [models.UniqueConstraint(fields=('publication', 'checksum_sha256'), name='uq_publication_checksum'), models.CheckConstraint(condition=models.Q(('file_size__gt', 0)), name='ck_document_size_positive')],
            },
        ),
    ]
