# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedocument',
            options={'verbose_name': '佐證文件', 'verbose_name_plural': '佐證文件'},
        ),
    ]
