# Generated by Django 5.2.17 on 2026-10-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_sourcedocument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedocument',
            name='document_type',
            field=models.CharField(choices=[('article_fulltext', '論文全文'), ('acceptance_letter', '接受函'), ('journal_proof', '期刊佐證'), ('index_proof', '索引佐證'), ('conference_proof', '會議佐證'), ('conference_evidence', '學術會議佐證'), ('other', '其他')], db_index=True, default='other', max_length=24),
        ),
    ]
